// All 50 US state capitals + DC as a static GeoJSON FeatureCollection.
// Used to power the "Capital Cities" toggle independently of the tile source,
// ensuring state capitals appear at any zoom level.
export const STATE_CAPITALS_GEOJSON: GeoJSON.FeatureCollection = {
  type: 'FeatureCollection',
  features: [
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-86.2999, 32.3668] }, properties: { name: 'Montgomery', state: 'Alabama' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-134.4197, 58.3005] }, properties: { name: 'Juneau', state: 'Alaska' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-112.0740, 33.4484] }, properties: { name: 'Phoenix', state: 'Arizona' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-92.2896, 34.7465] }, properties: { name: 'Little Rock', state: 'Arkansas' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-121.4944, 38.5816] }, properties: { name: 'Sacramento', state: 'California' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-104.9903, 39.7392] }, properties: { name: 'Denver', state: 'Colorado' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-72.6851, 41.7637] }, properties: { name: 'Hartford', state: 'Connecticut' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-75.5249, 39.1582] }, properties: { name: 'Dover', state: 'Delaware' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-84.2807, 30.4518] }, properties: { name: 'Tallahassee', state: 'Florida' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-84.3880, 33.7490] }, properties: { name: 'Atlanta', state: 'Georgia' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-157.8583, 21.3069] }, properties: { name: 'Honolulu', state: 'Hawaii' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-116.2023, 43.6150] }, properties: { name: 'Boise', state: 'Idaho' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-89.6501, 39.7983] }, properties: { name: 'Springfield', state: 'Illinois' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-86.1581, 39.7684] }, properties: { name: 'Indianapolis', state: 'Indiana' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-93.6091, 41.5908] }, properties: { name: 'Des Moines', state: 'Iowa' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-95.6890, 39.0489] }, properties: { name: 'Topeka', state: 'Kansas' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-84.8753, 38.2009] }, properties: { name: 'Frankfort', state: 'Kentucky' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-91.1871, 30.4515] }, properties: { name: 'Baton Rouge', state: 'Louisiana' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-69.7653, 44.3106] }, properties: { name: 'Augusta', state: 'Maine' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-76.4922, 38.9784] }, properties: { name: 'Annapolis', state: 'Maryland' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-71.0589, 42.3601] }, properties: { name: 'Boston', state: 'Massachusetts' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-84.5555, 42.7325] }, properties: { name: 'Lansing', state: 'Michigan' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-93.0900, 44.9537] }, properties: { name: 'Saint Paul', state: 'Minnesota' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-90.1848, 32.2988] }, properties: { name: 'Jackson', state: 'Mississippi' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-92.1735, 38.5767] }, properties: { name: 'Jefferson City', state: 'Missouri' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-112.0270, 46.5958] }, properties: { name: 'Helena', state: 'Montana' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-96.6852, 40.8136] }, properties: { name: 'Lincoln', state: 'Nebraska' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-119.7674, 39.1638] }, properties: { name: 'Carson City', state: 'Nevada' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-71.5376, 43.2081] }, properties: { name: 'Concord', state: 'New Hampshire' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-74.7597, 40.2171] }, properties: { name: 'Trenton', state: 'New Jersey' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-105.9378, 35.6870] }, properties: { name: 'Santa Fe', state: 'New Mexico' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-73.7562, 42.6526] }, properties: { name: 'Albany', state: 'New York' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-78.6382, 35.7796] }, properties: { name: 'Raleigh', state: 'North Carolina' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-100.7837, 46.8083] }, properties: { name: 'Bismarck', state: 'North Dakota' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-83.0007, 39.9612] }, properties: { name: 'Columbus', state: 'Ohio' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-97.5164, 35.4676] }, properties: { name: 'Oklahoma City', state: 'Oklahoma' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-123.0351, 44.9429] }, properties: { name: 'Salem', state: 'Oregon' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-76.8844, 40.2732] }, properties: { name: 'Harrisburg', state: 'Pennsylvania' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-71.4128, 41.8240] }, properties: { name: 'Providence', state: 'Rhode Island' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-81.0348, 34.0007] }, properties: { name: 'Columbia', state: 'South Carolina' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-100.3463, 44.3683] }, properties: { name: 'Pierre', state: 'South Dakota' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-86.7816, 36.1627] }, properties: { name: 'Nashville', state: 'Tennessee' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-97.7431, 30.2672] }, properties: { name: 'Austin', state: 'Texas' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-111.8910, 40.7608] }, properties: { name: 'Salt Lake City', state: 'Utah' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-72.5754, 44.2601] }, properties: { name: 'Montpelier', state: 'Vermont' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-77.4360, 37.5407] }, properties: { name: 'Richmond', state: 'Virginia' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-122.9007, 47.0379] }, properties: { name: 'Olympia', state: 'Washington' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-81.6326, 38.3498] }, properties: { name: 'Charleston', state: 'West Virginia' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-89.4012, 43.0731] }, properties: { name: 'Madison', state: 'Wisconsin' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-104.8202, 41.1400] }, properties: { name: 'Cheyenne', state: 'Wyoming' } },
    { type: 'Feature', geometry: { type: 'Point', coordinates: [-77.0369, 38.9072] }, properties: { name: 'Washington', state: 'D.C.' } },
  ],
};
