// Generated by scripts/process-mockups.mjs — do not edit by hand.
// Bounding box of the print area in each mockup, as fractions of the
// image dimensions. Use to position the user's preview behind the mockup.

export interface MockupArea { x: number; y: number; w: number; h: number }

export const MOCKUP_AREAS: Record<string, MockupArea> = {
  "prodigi-global-cfp-18x24-black-frame.png": {
    "x": 0.408203125,
    "y": 0.21484375,
    "w": 0.1806640625,
    "h": 0.2412109375
  },
  "prodigi-global-cfp-18x24-black-frame__1_.png": {
    "x": 0.208984375,
    "y": 0.1123046875,
    "w": 0.5810546875,
    "h": 0.7744140625
  },
  "prodigi-global-cfp-18x24-natural-frame.png": {
    "x": 0.208984375,
    "y": 0.1123046875,
    "w": 0.5810546875,
    "h": 0.7744140625
  },
  "prodigi-global-cfp-18x24-natural-frame__1_.png": {
    "x": 0.408203125,
    "y": 0.21484375,
    "w": 0.1806640625,
    "h": 0.2412109375
  },
  "prodigi-global-cfp-18x24-white-frame.png": {
    "x": 0.208984375,
    "y": 0.1123046875,
    "w": 0.5810546875,
    "h": 0.7744140625
  },
  "prodigi-global-cfp-18x24-white-frame__1_.png": {
    "x": 0.408203125,
    "y": 0.2138671875,
    "w": 0.1806640625,
    "h": 0.2421875
  },
  "prodigi-global-cfp-20x20-black-frame.png": {
    "x": 0.11328125,
    "y": 0.11328125,
    "w": 0.775390625,
    "h": 0.775390625
  },
  "prodigi-global-cfp-20x20-black-frame__1_.png": {
    "x": 0.3974609375,
    "y": 0.2353515625,
    "w": 0.2021484375,
    "h": 0.201171875
  },
  "prodigi-global-cfp-20x20-natural-frame.png": {
    "x": 0.11328125,
    "y": 0.11328125,
    "w": 0.775390625,
    "h": 0.775390625
  },
  "prodigi-global-cfp-20x20-natural-frame__1_.png": {
    "x": 0.3974609375,
    "y": 0.2353515625,
    "w": 0.2021484375,
    "h": 0.201171875
  },
  "prodigi-global-cfp-20x20-white-frame.png": {
    "x": 0.11328125,
    "y": 0.11328125,
    "w": 0.775390625,
    "h": 0.775390625
  },
  "prodigi-global-cfp-20x20-white-frame__1_.png": {
    "x": 0.3974609375,
    "y": 0.2353515625,
    "w": 0.2021484375,
    "h": 0.201171875
  },
  "prodigi-global-cfp-24x18-black-frame.png": {
    "x": 0.1123046875,
    "y": 0.208984375,
    "w": 0.7744140625,
    "h": 0.5810546875
  },
  "prodigi-global-cfp-24x18-black-frame__1_.png": {
    "x": 0.376953125,
    "y": 0.2451171875,
    "w": 0.2431640625,
    "h": 0.1806640625
  },
  "prodigi-global-cfp-24x18-natural-frame.png": {
    "x": 0.1123046875,
    "y": 0.208984375,
    "w": 0.7744140625,
    "h": 0.5810546875
  },
  "prodigi-global-cfp-24x18-natural-frame__1_.png": {
    "x": 0.376953125,
    "y": 0.2451171875,
    "w": 0.2431640625,
    "h": 0.1806640625
  },
  "prodigi-global-cfp-24x18-white-frame.png": {
    "x": 0.1123046875,
    "y": 0.208984375,
    "w": 0.7744140625,
    "h": 0.5810546875
  },
  "prodigi-global-cfp-24x18-white-frame__1_.png": {
    "x": 0.376953125,
    "y": 0.2451171875,
    "w": 0.2431640625,
    "h": 0.1806640625
  },
  "prodigi-global-cfpm-18x24-black-frame-snow-white-mount.png": {
    "x": 0.2744140625,
    "y": 0.177734375,
    "w": 0.451171875,
    "h": 0.6435546875
  },
  "prodigi-global-cfpm-18x24-black-frame-snow-white-mount__1_.png": {
    "x": 0.4287109375,
    "y": 0.2353515625,
    "w": 0.1396484375,
    "h": 0.19921875
  },
  "prodigi-global-cfpm-18x24-natural-frame-snow-white-mount.png": {
    "x": 0.2744140625,
    "y": 0.177734375,
    "w": 0.451171875,
    "h": 0.6435546875
  },
  "prodigi-global-cfpm-18x24-natural-frame-snow-white-mount__1_.png": {
    "x": 0.4287109375,
    "y": 0.2353515625,
    "w": 0.1396484375,
    "h": 0.19921875
  },
  "prodigi-global-cfpm-18x24-white-frame-snow-white-mount.png": {
    "x": 0.2744140625,
    "y": 0.177734375,
    "w": 0.451171875,
    "h": 0.6435546875
  },
  "prodigi-global-cfpm-18x24-white-frame-snow-white-mount__1_.png": {
    "x": 0.4287109375,
    "y": 0.2353515625,
    "w": 0.1396484375,
    "h": 0.19921875
  },
  "prodigi-global-cfpm-20x20-black-frame-snow-white-mount.png": {
    "x": 0.1904296875,
    "y": 0.1904296875,
    "w": 0.6181640625,
    "h": 0.619140625
  },
  "prodigi-global-cfpm-20x20-black-frame-snow-white-mount__1_.png": {
    "x": 0.41796875,
    "y": 0.255859375,
    "w": 0.1611328125,
    "h": 0.1591796875
  },
  "prodigi-global-cfpm-20x20-natural-frame-snow-white-mount.png": {
    "x": 0.1904296875,
    "y": 0.1904296875,
    "w": 0.6181640625,
    "h": 0.619140625
  },
  "prodigi-global-cfpm-20x20-natural-frame-snow-white-mount__1_.png": {
    "x": 0.41796875,
    "y": 0.255859375,
    "w": 0.1611328125,
    "h": 0.1591796875
  },
  "prodigi-global-cfpm-20x20-white-frame-snow-white-mount.png": {
    "x": 0.1904296875,
    "y": 0.1904296875,
    "w": 0.6181640625,
    "h": 0.619140625
  },
  "prodigi-global-cfpm-20x20-white-frame-snow-white-mount__1_.png": {
    "x": 0.41796875,
    "y": 0.255859375,
    "w": 0.1611328125,
    "h": 0.1591796875
  },
  "prodigi-global-cfpm-24x18-black-frame-snow-white-mount.png": {
    "x": 0.177734375,
    "y": 0.2744140625,
    "w": 0.6435546875,
    "h": 0.451171875
  },
  "prodigi-global-cfpm-24x18-black-frame-snow-white-mount__1_.png": {
    "x": 0.3974609375,
    "y": 0.265625,
    "w": 0.201171875,
    "h": 0.1396484375
  },
  "prodigi-global-cfpm-24x18-natural-frame-snow-white-mount.png": {
    "x": 0.177734375,
    "y": 0.2744140625,
    "w": 0.6435546875,
    "h": 0.451171875
  },
  "prodigi-global-cfpm-24x18-natural-frame-snow-white-mount__1_.png": {
    "x": 0.3974609375,
    "y": 0.265625,
    "w": 0.201171875,
    "h": 0.1396484375
  },
  "prodigi-global-cfpm-24x18-white-frame-snow-white-mount.png": {
    "x": 0.177734375,
    "y": 0.2744140625,
    "w": 0.6435546875,
    "h": 0.451171875
  },
  "prodigi-global-cfpm-24x18-white-frame-snow-white-mount__1_.png": {
    "x": 0.3974609375,
    "y": 0.265625,
    "w": 0.201171875,
    "h": 0.1396484375
  }
};
