// Generated by scripts/process-mockups.mjs — do not edit by hand.
// Bounding box of the print area in each mockup, as fractions of the
// image dimensions. Use to position the user's preview behind the mockup.

export interface MockupArea { x: number; y: number; w: number; h: number }

export const MOCKUP_AREAS: Record<string, MockupArea> = {
  "prodigi-global-cfp-18x24-black-frame.png": {
    "x": 0.4033203125,
    "y": 0.2099609375,
    "w": 0.1904296875,
    "h": 0.2509765625
  },
  "prodigi-global-cfp-18x24-black-frame__1_.png": {
    "x": 0.2041015625,
    "y": 0.107421875,
    "w": 0.5908203125,
    "h": 0.7841796875
  },
  "prodigi-global-cfp-18x24-natural-frame.png": {
    "x": 0.2041015625,
    "y": 0.107421875,
    "w": 0.5908203125,
    "h": 0.7841796875
  },
  "prodigi-global-cfp-18x24-natural-frame__1_.png": {
    "x": 0.4033203125,
    "y": 0.2099609375,
    "w": 0.1904296875,
    "h": 0.2509765625
  },
  "prodigi-global-cfp-18x24-white-frame.png": {
    "x": 0.2041015625,
    "y": 0.107421875,
    "w": 0.5908203125,
    "h": 0.7841796875
  },
  "prodigi-global-cfp-18x24-white-frame__1_.png": {
    "x": 0.4033203125,
    "y": 0.208984375,
    "w": 0.1904296875,
    "h": 0.251953125
  },
  "prodigi-global-cfp-20x20-black-frame.png": {
    "x": 0.1083984375,
    "y": 0.1083984375,
    "w": 0.78515625,
    "h": 0.78515625
  },
  "prodigi-global-cfp-20x20-black-frame__1_.png": {
    "x": 0.392578125,
    "y": 0.23046875,
    "w": 0.2119140625,
    "h": 0.2109375
  },
  "prodigi-global-cfp-20x20-natural-frame.png": {
    "x": 0.1083984375,
    "y": 0.1083984375,
    "w": 0.78515625,
    "h": 0.78515625
  },
  "prodigi-global-cfp-20x20-natural-frame__1_.png": {
    "x": 0.392578125,
    "y": 0.23046875,
    "w": 0.2119140625,
    "h": 0.2109375
  },
  "prodigi-global-cfp-20x20-white-frame.png": {
    "x": 0.1083984375,
    "y": 0.1083984375,
    "w": 0.78515625,
    "h": 0.78515625
  },
  "prodigi-global-cfp-20x20-white-frame__1_.png": {
    "x": 0.392578125,
    "y": 0.23046875,
    "w": 0.2119140625,
    "h": 0.2109375
  },
  "prodigi-global-cfp-24x18-black-frame.png": {
    "x": 0.107421875,
    "y": 0.2041015625,
    "w": 0.7841796875,
    "h": 0.5908203125
  },
  "prodigi-global-cfp-24x18-black-frame__1_.png": {
    "x": 0.3720703125,
    "y": 0.240234375,
    "w": 0.2529296875,
    "h": 0.1904296875
  },
  "prodigi-global-cfp-24x18-natural-frame.png": {
    "x": 0.107421875,
    "y": 0.2041015625,
    "w": 0.7841796875,
    "h": 0.5908203125
  },
  "prodigi-global-cfp-24x18-natural-frame__1_.png": {
    "x": 0.3720703125,
    "y": 0.240234375,
    "w": 0.2529296875,
    "h": 0.1904296875
  },
  "prodigi-global-cfp-24x18-white-frame.png": {
    "x": 0.107421875,
    "y": 0.2041015625,
    "w": 0.7841796875,
    "h": 0.5908203125
  },
  "prodigi-global-cfp-24x18-white-frame__1_.png": {
    "x": 0.3720703125,
    "y": 0.240234375,
    "w": 0.2529296875,
    "h": 0.1904296875
  },
  "prodigi-global-cfpm-18x24-black-frame-snow-white-mount.png": {
    "x": 0.26953125,
    "y": 0.1728515625,
    "w": 0.4609375,
    "h": 0.6533203125
  },
  "prodigi-global-cfpm-18x24-black-frame-snow-white-mount__1_.png": {
    "x": 0.423828125,
    "y": 0.23046875,
    "w": 0.1494140625,
    "h": 0.208984375
  },
  "prodigi-global-cfpm-18x24-natural-frame-snow-white-mount.png": {
    "x": 0.26953125,
    "y": 0.1728515625,
    "w": 0.4609375,
    "h": 0.6533203125
  },
  "prodigi-global-cfpm-18x24-natural-frame-snow-white-mount__1_.png": {
    "x": 0.423828125,
    "y": 0.23046875,
    "w": 0.1494140625,
    "h": 0.208984375
  },
  "prodigi-global-cfpm-18x24-white-frame-snow-white-mount.png": {
    "x": 0.26953125,
    "y": 0.1728515625,
    "w": 0.4609375,
    "h": 0.6533203125
  },
  "prodigi-global-cfpm-18x24-white-frame-snow-white-mount__1_.png": {
    "x": 0.423828125,
    "y": 0.23046875,
    "w": 0.1494140625,
    "h": 0.208984375
  },
  "prodigi-global-cfpm-20x20-black-frame-snow-white-mount.png": {
    "x": 0.185546875,
    "y": 0.185546875,
    "w": 0.6279296875,
    "h": 0.62890625
  },
  "prodigi-global-cfpm-20x20-black-frame-snow-white-mount__1_.png": {
    "x": 0.4130859375,
    "y": 0.2509765625,
    "w": 0.1708984375,
    "h": 0.1689453125
  },
  "prodigi-global-cfpm-20x20-natural-frame-snow-white-mount.png": {
    "x": 0.185546875,
    "y": 0.185546875,
    "w": 0.6279296875,
    "h": 0.62890625
  },
  "prodigi-global-cfpm-20x20-natural-frame-snow-white-mount__1_.png": {
    "x": 0.4130859375,
    "y": 0.2509765625,
    "w": 0.1708984375,
    "h": 0.1689453125
  },
  "prodigi-global-cfpm-20x20-white-frame-snow-white-mount.png": {
    "x": 0.185546875,
    "y": 0.185546875,
    "w": 0.6279296875,
    "h": 0.62890625
  },
  "prodigi-global-cfpm-20x20-white-frame-snow-white-mount__1_.png": {
    "x": 0.4130859375,
    "y": 0.2509765625,
    "w": 0.1708984375,
    "h": 0.1689453125
  },
  "prodigi-global-cfpm-24x18-black-frame-snow-white-mount.png": {
    "x": 0.1728515625,
    "y": 0.26953125,
    "w": 0.6533203125,
    "h": 0.4609375
  },
  "prodigi-global-cfpm-24x18-black-frame-snow-white-mount__1_.png": {
    "x": 0.392578125,
    "y": 0.2607421875,
    "w": 0.2109375,
    "h": 0.1494140625
  },
  "prodigi-global-cfpm-24x18-natural-frame-snow-white-mount.png": {
    "x": 0.1728515625,
    "y": 0.26953125,
    "w": 0.6533203125,
    "h": 0.4609375
  },
  "prodigi-global-cfpm-24x18-natural-frame-snow-white-mount__1_.png": {
    "x": 0.392578125,
    "y": 0.2607421875,
    "w": 0.2109375,
    "h": 0.1494140625
  },
  "prodigi-global-cfpm-24x18-white-frame-snow-white-mount.png": {
    "x": 0.1728515625,
    "y": 0.26953125,
    "w": 0.6533203125,
    "h": 0.4609375
  },
  "prodigi-global-cfpm-24x18-white-frame-snow-white-mount__1_.png": {
    "x": 0.392578125,
    "y": 0.2607421875,
    "w": 0.2109375,
    "h": 0.1494140625
  }
};
