const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.TERRALIS_TEST_URL || 'http://localhost:3000';
(async () => {
  const browser = await chromium.launch({headless: true});
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  const page = await context.newPage();
  const errors=[]; page.on('pageerror', e => errors.push(e.message));
  const readScene = () => page.evaluate(() => JSON.parse(sessionStorage.getItem('teralis:print-scene')));
  const ready = async () => { await page.getByRole('button',{name:'Choose size & frame',exact:true}).waitFor(); await page.waitForFunction(()=> [...document.querySelectorAll('button')].some(b=>b.textContent==='Choose size & frame' && !b.disabled),{},{timeout:45000}); };
  await page.goto(`${base}/maps/chicago-il?look=on-water&palette=navy`);
  await ready();
  await page.waitForFunction(()=>JSON.parse(sessionStorage.getItem('teralis:print-scene')).title.onWater);
  assert.equal((await readScene()).paletteId,'navy');
  await page.screenshot({path:'/tmp/terralis-city-desktop.png'});
  // Capture the exact advertised composition from the same proof pipeline.
  await page.getByRole('button',{name:'Choose size & frame',exact:true}).click();
  await page.waitForURL('**/size?**',{timeout:45000});
  assert.match(page.url(),/print=chicago-il/);
  const proof = await page.evaluate(()=>{const key=Object.keys(sessionStorage).find(k=>{try{return JSON.parse(sessionStorage.getItem(k)).dataUrl?.startsWith('data:image/')}catch{return false}});return JSON.parse(sessionStorage.getItem(key)).dataUrl;});
  if (process.env.UPDATE_MARKETING_ART === '1') fs.writeFileSync('public/thumbnails/chicago-open-water.png',Buffer.from(proof.split(',')[1],'base64'));
  await page.goBack(); await ready();
  await page.getByText('Edit wording',{exact:true}).click();
  await page.getByRole('textbox',{name:'Title',exact:true}).fill('Our Chicago');
  await page.getByRole('textbox',{name:/Dedication or subtitle/}).fill('The place we call home');
  await page.getByRole('button',{name:'Red',exact:true}).click();
  await page.waitForTimeout(700);
  let scene=await readScene(); assert.equal(scene.title.text,'Our Chicago'); assert.equal(scene.title.subtitle,'The place we call home'); assert.equal(scene.paletteId,'crimson');
  const saved=page.url(); await page.reload(); await ready();
  assert.equal((await readScene()).title.text,'Our Chicago');
  const shared=await context.newPage(); await shared.goto(saved); await shared.waitForFunction(()=>JSON.parse(sessionStorage.getItem('teralis:print-scene'))?.title.text==='Our Chicago'); await shared.close();
  console.log('PASS city ad entry, proof handoff, personal wording, palette, reload and shared link');
  await page.goto(`${base}/maps/wisconsin?edition=atlas`); await ready();
  await page.getByText('Map detail & shape',{exact:true}).click();
  await page.getByRole('button',{name:'Cities & towns',exact:true}).click();
  await page.waitForTimeout(500);
  scene=await readScene(); assert.equal(scene.detail.labels.towns,true); assert.equal(scene.detail.labels.cities,true); assert.equal(scene.detail.places,'neutral');
  await page.getByRole('button',{name:/Topographic Elevation/}).click(); await ready();
  scene=await readScene(); assert.equal(scene.region.theme,'topographic'); assert.equal(scene.detail.roads,'none'); assert.equal(scene.detail.rivers,true);
  await page.screenshot({path:'/tmp/terralis-state-desktop.png'});
  console.log('PASS state editions and cities/towns control');
  await page.goto(`${base}/maps/tennessee?edition=illustrated`); await ready();
  assert.equal((await readScene()).region.theme,'illustrated');
  assert.equal(await page.locator('.place-stage img').evaluate(i=>i.complete && i.naturalWidth>0),true);
  await page.screenshot({path:'/tmp/terralis-illustrated-desktop.png'});
  await page.getByText('Edit wording',{exact:true}).click();
  await page.getByRole('textbox',{name:'Title',exact:true}).fill('Home in Tennessee');
  await page.getByRole('button',{name:'Choose size & frame',exact:true}).click(); await page.waitForURL('**/size?**',{timeout:45000});
  assert.match(page.url(),/print=tennessee/); assert.match(page.url(),/o=landscape/); assert.equal((await readScene()).title.text,'Home in Tennessee');
  console.log('PASS illustrated asset, caption and landscape proof handoff');
  await page.setViewportSize({width:390,height:844}); await page.goto(base);
  await page.getByRole('combobox').fill('Wisconsin');
  await page.getByRole('option').filter({hasText:'Wisconsin'}).first().click();
  await page.waitForURL('**/maps/wisconsin**'); await ready();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true);
  await page.screenshot({path:'/tmp/terralis-state-mobile.png',fullPage:true});
  await page.goto(`${base}/maps/tennessee?edition=illustrated`); await ready();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true);
  await page.screenshot({path:'/tmp/terralis-illustrated-mobile.png',fullPage:true});
  console.log('PASS mobile search-to-state navigation and overflow');
  assert.deepEqual(errors,[]);
  console.log('PASS no browser runtime errors');
  await browser.close();
})().catch(err=>{console.error(err);process.exit(1)});
