// One-time preprocessor for Prodigi mockup PNGs.
//
// For each PNG in public/mockups/wall/:
//   1. Detect the bounding box of the neon-pink print area (the placeholder
//      uploaded into Prodigi's mockup generator).
//   2. Replace pink pixels with full transparency so the user's actual map
//      preview can show through.
//   3. Write the cleaned PNG back in place.
//   4. Emit src/lib/print/mockupAreas.generated.ts — a typed map of
//      { filename → { x, y, w, h } } in normalised [0,1] coords so the UI
//      can position the preview behind the mockup.
//
// Run with:  npm run process-mockups
//
// Idempotent: pixels already transparent are skipped. Safe to re-run.

import sharp from 'sharp';
import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname  = path.dirname(fileURLToPath(import.meta.url));
const MOCKUP_DIR = path.resolve(__dirname, '../public/mockups/wall');
const OUT_TS     = path.resolve(__dirname, '../src/lib/print/mockupAreas.generated.ts');

// Magenta print is roughly RGB(255, 0, 200). "Pinkness score" works well
// because no realistic scene color (wood, plants, walls, fabric) has both
// high R and high B with low G.
function pinkScore(r, g, b) {
  return (r + b) - 2 * g;
}
function isPink(r, g, b) {
  // Strict: definite pink interior — RGB averages ~(255, 0, 200) → score 710
  return pinkScore(r, g, b) > 200 && b > 100;
}
function isPinkHalo(r, g, b) {
  // Loose: anti-aliased edge pixels mixed with frame colour
  return pinkScore(r, g, b) > 60 && b > 50;
}

async function processOne(filename) {
  const filepath = path.join(MOCKUP_DIR, filename);
  const img = sharp(filepath).ensureAlpha();
  const { data, info } = await img.raw().toBuffer({ resolveWithObject: true });
  const { width, height, channels } = info;

  // Pass 1 — strict detection. Records bbox, marks definite pink transparent.
  const transparentMask = new Uint8Array(width * height);
  let minX = width, minY = height, maxX = -1, maxY = -1;
  let pinkCount = 0;

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const i = (y * width + x) * channels;
      const r = data[i], g = data[i + 1], b = data[i + 2];
      if (isPink(r, g, b)) {
        if (x < minX) minX = x;
        if (y < minY) minY = y;
        if (x > maxX) maxX = x;
        if (y > maxY) maxY = y;
        data[i + 3] = 0;
        transparentMask[y * width + x] = 1;
        pinkCount++;
      }
    }
  }

  // Pass 2 — within bbox, sweep any halo pixel adjacent to a transparent
  // neighbour. Three iterations handles up to a 3-px wide anti-alias ring.
  if (pinkCount > 0) {
    for (let iter = 0; iter < 3; iter++) {
      const additions = [];
      for (let y = minY; y <= maxY; y++) {
        for (let x = minX; x <= maxX; x++) {
          const idx = y * width + x;
          if (transparentMask[idx]) continue;
          // Has at least one transparent neighbour?
          const neigh =
            (x > 0       && transparentMask[idx - 1]) ||
            (x < width-1 && transparentMask[idx + 1]) ||
            (y > 0       && transparentMask[idx - width]) ||
            (y < height-1 && transparentMask[idx + width]);
          if (!neigh) continue;
          const i = idx * channels;
          const r = data[i], g = data[i + 1], b = data[i + 2];
          if (isPinkHalo(r, g, b)) additions.push(idx);
        }
      }
      if (additions.length === 0) break;
      for (const idx of additions) {
        transparentMask[idx] = 1;
        data[idx * channels + 3] = 0;
      }
    }
  }

  if (pinkCount === 0) {
    console.log(`  skip  ${filename} — no pink found (already processed?)`);
    return null;
  }

  await sharp(data, { raw: { width, height, channels } })
    .png({ compressionLevel: 9 })
    .toFile(filepath);

  const bbox = {
    x: minX / width,
    y: minY / height,
    w: (maxX - minX + 1) / width,
    h: (maxY - minY + 1) / height,
  };

  console.log(
    `  done  ${filename}  ${pinkCount}px  bbox(${bbox.x.toFixed(3)},${bbox.y.toFixed(3)} ${bbox.w.toFixed(3)}×${bbox.h.toFixed(3)})`
  );
  return bbox;
}

async function main() {
  const files = (await readdir(MOCKUP_DIR))
    .filter((f) => f.endsWith('.png'))
    .sort();

  console.log(`Processing ${files.length} mockups in ${MOCKUP_DIR}\n`);

  const areas = {};
  for (const f of files) {
    const bbox = await processOne(f);
    if (bbox) areas[f] = bbox;
  }

  const tsSource =
    `// Generated by scripts/process-mockups.mjs — do not edit by hand.\n` +
    `// Bounding box of the print area in each mockup, as fractions of the\n` +
    `// image dimensions. Use to position the user's preview behind the mockup.\n\n` +
    `export interface MockupArea { x: number; y: number; w: number; h: number }\n\n` +
    `export const MOCKUP_AREAS: Record<string, MockupArea> = ${JSON.stringify(areas, null, 2)};\n`;

  await writeFile(OUT_TS, tsSource, 'utf8');
  console.log(`\nWrote ${Object.keys(areas).length} entries → ${OUT_TS}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
